#Preserve "white" spaces on empty lines.
default: &default
    configCache: false
    tmpdir: {API_PROJECT_DIR}tmp/
    
    hosts:
        modmon2.lo:
    
    exceptionhandler:
        "*": default
    
    lang:
        dir: {API_PROJECT_DIR}lang
        fileprefix: lang
        i18ntransform: true
        default: en
        languages: [en]
        retriever: lowercase
    
    db:
        default,write:
            driver: doctrine
            dsn: mysql://modmon2:20modmon08@localhost/mo
            modeldir: localinc/api/model/data            